Run npx --no-install next build ⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache Attention: Next.js now collects completely anonymous telemetry regarding usage. This information is used to shape Next.js' roadmap and prioritize features. You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL: https://nextjs.org/telemetry
   ▲ Next.js 15.2.3

   Creating an optimized production build ...

Retrying 1/3...
 ✓ Compiled successfully
   Linting and checking validity of types ...
Failed to compile.

./src/lib/data.ts:2:10
Type error: Variable 'db' implicitly has type 'any' in some locations where its type cannot be determined.

  1 |
> 2 | import { db } from './firebase';
    |          ^
  3 | import {
  4 |   collection,
  5 |   getDocs,
Next.js build worker exited with code: 1 and signal: null
Error: Process completed with exit code 1.